/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 car.glb -t 
Author: Martin Trafas (https://sketchfab.com/Bexxie)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/chevrolet-corvette-c7-2b509d1bce104224b147c81757f6f43a
Title: Chevrolet Corvette (C7)
*/

import * as THREE from 'three'
import React, { Ref, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Brake_Disc_FL_Brake_Disc_0: THREE.Mesh
    Tire_FL_TireMaterial_0: THREE.Mesh
    Rim_FL_Rim_0: THREE.Mesh
    Rim_FL_Lug_Nuts_0: THREE.Mesh
    Rim_FL_CorvetteWingEmblem_0: THREE.Mesh
    Brake_Caliper_FL_Brake_Caliper_0: THREE.Mesh
    Brake_Disc_RL_Brake_Disc_0: THREE.Mesh
    Tire_RL_TireMaterial_0: THREE.Mesh
    Rim_RL_Rim_0: THREE.Mesh
    Rim_RL_Lug_Nuts_0: THREE.Mesh
    Rim_RL_CorvetteWingEmblem_0: THREE.Mesh
    Brake_Caliper_RL_Brake_Caliper_0: THREE.Mesh
    Brake_Disc_RR_Brake_Disc_0: THREE.Mesh
    Tire_RR_TireMaterial_0: THREE.Mesh
    Rim_RR_Rim_0: THREE.Mesh
    Rim_RR_Lug_Nuts_0: THREE.Mesh
    Rim_RR_CorvetteWingEmblem_0: THREE.Mesh
    Brake_Caliper_RR_Brake_Caliper_0: THREE.Mesh
    Brake_Disc_FR_Brake_Disc_0: THREE.Mesh
    Tire_FR_TireMaterial_0: THREE.Mesh
    Rim_FR_Rim_0: THREE.Mesh
    Rim_FR_Lug_Nuts_0: THREE.Mesh
    Rim_FR_CorvetteWingEmblem_0: THREE.Mesh
    Brake_Caliper_FR_Brake_Caliper_0: THREE.Mesh
    CarBody_2_Glossy_Plastic_0: THREE.Mesh
    CarBody_2_Plastic_0: THREE.Mesh
    CarBody_2_Rubber_0: THREE.Mesh
    CarBody_2_WindowBorder_0: THREE.Mesh
    CarBody_2_Wipers_0: THREE.Mesh
    CarBody_2_CorvetteWingEmblem_0: THREE.Mesh
    CarBody_2_Chrome_0: THREE.Mesh
    CarBody_2_Shadow_0: THREE.Mesh
    CarBody_2_Mesh_0: THREE.Mesh
    CarBody_2_Side_Mirrors_0: THREE.Mesh
    CarBody_2_Reflectors_0: THREE.Mesh
    CarBody_2_Tail_Lights_White_Cover_0: THREE.Mesh
    CarBody_2_Tail_Lights_Red_Cover_0: THREE.Mesh
    CarBody_2_Daylight_Cover_0: THREE.Mesh
    CarBody_2_Spoiler_Light_Cover_0: THREE.Mesh
    CarBody_2_Main_Headlight_Lens_0: THREE.Mesh
    CarBody_2_Blinker_Glass_Cover_0: THREE.Mesh
    CarBody_2_Tail_Lights_Red_Cover_2_0: THREE.Mesh
    CarBody_2_Side_Reflectors_Cover_0: THREE.Mesh
    CarBody_2_Windows_0: THREE.Mesh
    CarBody_2_Headlight_Cover_0: THREE.Mesh
    CarBody_2_Exhaust_0: THREE.Mesh
    CarBody_2_Exhaust_Housing_0: THREE.Mesh
    CarBody_2_Interior_0: THREE.Mesh
    CarBody_1_Car_Paint_0: THREE.Mesh
    CarBody_1_Car_Paint_0_1: THREE.Mesh
    CarBody_1_Car_Paint_0_2: THREE.Mesh
    CarBody_1_Car_Paint_2_0: THREE.Mesh
    CarBody_3_Undercarriage_0: THREE.Mesh
    License_Plate_LicensePlate_Frame_0: THREE.Mesh
    License_Plate_License_Plate_0: THREE.Mesh
  }
  materials: {
    Brake_Disc: THREE.MeshStandardMaterial
    TireMaterial: THREE.MeshStandardMaterial
    material: THREE.MeshPhysicalMaterial
    Lug_Nuts: THREE.MeshStandardMaterial
    CorvetteWingEmblem: THREE.MeshStandardMaterial
    Brake_Caliper: THREE.MeshStandardMaterial
    Glossy_Plastic: THREE.MeshStandardMaterial
    Plastic: THREE.MeshStandardMaterial
    Rubber: THREE.MeshStandardMaterial
    WindowBorder: THREE.MeshStandardMaterial
    Wipers: THREE.MeshStandardMaterial
    Chrome: THREE.MeshStandardMaterial
    Shadow: THREE.MeshStandardMaterial
    Mesh: THREE.MeshStandardMaterial
    Side_Mirrors: THREE.MeshStandardMaterial
    Reflectors: THREE.MeshStandardMaterial
    Tail_Lights_White_Cover: THREE.MeshPhysicalMaterial
    Tail_Lights_Red_Cover: THREE.MeshPhysicalMaterial
    Daylight_Cover: THREE.MeshPhysicalMaterial
    Spoiler_Light_Cover: THREE.MeshStandardMaterial
    Main_Headlight_Lens: THREE.MeshPhysicalMaterial
    Blinker_Glass_Cover: THREE.MeshPhysicalMaterial
    Tail_Lights_Red_Cover_2: THREE.MeshPhysicalMaterial
    Side_Reflectors_Cover: THREE.MeshPhysicalMaterial
    Windows: THREE.MeshStandardMaterial
    Headlight_Cover: THREE.MeshPhysicalMaterial
    Exhaust: THREE.MeshStandardMaterial
    Exhaust_Housing: THREE.MeshStandardMaterial
    Interior: THREE.MeshStandardMaterial
    Car_Paint: THREE.MeshPhysicalMaterial
    Car_Paint_2: THREE.MeshPhysicalMaterial
    Undercarriage: THREE.MeshStandardMaterial
    LicensePlate_Frame: THREE.MeshStandardMaterial
    License_Plate: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationAction[]
}





export const CarModel = React.forwardRef<THREE.Group,JSX.IntrinsicElements['group']>((props, ref) => {
  const { nodes, materials,animations  } = useGLTF('/models/car.glb') as unknown as GLTFResult
  const {actions, names} = useAnimations(animations, ref as any);


  return (
    <group ref={ref} {...props} dispose={null}>
      <group position={[1.6, 0.76, 2.68]} rotation={[2.199, Math.PI / 2, 0]} scale={[1, 1, 1.1]}>
        <mesh geometry={nodes.Rim_FL_Rim_0.geometry} material={materials.material} />
        <mesh geometry={nodes.Rim_FL_Lug_Nuts_0.geometry} material={materials.Lug_Nuts} />
        <mesh geometry={nodes.Rim_FL_CorvetteWingEmblem_0.geometry} material={materials.CorvetteWingEmblem} />
        <mesh geometry={nodes.Brake_Disc_FL_Brake_Disc_0.geometry} material={materials.Brake_Disc} rotation={[0, 0, 2.513]} scale={0.402} />
        <mesh geometry={nodes.Tire_FL_TireMaterial_0.geometry} material={materials.TireMaterial} rotation={[Math.PI / 2, 0.942, Math.PI / 2]} />
      </group>
      <group position={[1.7, 0.76, -2.7]} rotation={[2.199, Math.PI / 2, 0]} scale={[1, 1, 1.1]}>
        <mesh geometry={nodes.Rim_RL_Rim_0.geometry} material={materials.material} />
        <mesh geometry={nodes.Rim_RL_Lug_Nuts_0.geometry} material={materials.Lug_Nuts} />
        <mesh geometry={nodes.Rim_RL_CorvetteWingEmblem_0.geometry} material={materials.CorvetteWingEmblem} />
        <mesh geometry={nodes.Brake_Disc_RL_Brake_Disc_0.geometry} material={materials.Brake_Disc} rotation={[0, 0, 2.513]} scale={0.402} />
        <mesh geometry={nodes.Tire_RL_TireMaterial_0.geometry} material={materials.TireMaterial} rotation={[Math.PI / 2, 0.942, Math.PI / 2]} />
      </group>
      <group position={[-1.59, 0.76, -2.7]} rotation={[-2.199, -Math.PI / 2, 0]} scale={[1, 1, 1.1]}>
        <mesh geometry={nodes.Rim_RR_Rim_0.geometry} material={materials.material} />
        <mesh geometry={nodes.Rim_RR_Lug_Nuts_0.geometry} material={materials.Lug_Nuts} />
        <mesh geometry={nodes.Rim_RR_CorvetteWingEmblem_0.geometry} material={materials.CorvetteWingEmblem} />
        <mesh geometry={nodes.Brake_Disc_RR_Brake_Disc_0.geometry} material={materials.Brake_Disc} rotation={[0, 0, 2.513]} scale={0.402} />
        <mesh geometry={nodes.Tire_RR_TireMaterial_0.geometry} material={materials.TireMaterial} rotation={[Math.PI / 2, 0.942, Math.PI / 2]} />
      </group>
      <group position={[-1.59, 0.76, 2.68]} rotation={[-2.199, -Math.PI / 2, 0]} scale={[1, 1, 1.1]}>
        <mesh geometry={nodes.Rim_FR_Rim_0.geometry} material={materials.material} />
        <mesh geometry={nodes.Rim_FR_Lug_Nuts_0.geometry} material={materials.Lug_Nuts} />
        <mesh geometry={nodes.Rim_FR_CorvetteWingEmblem_0.geometry} material={materials.CorvetteWingEmblem} />
        <mesh geometry={nodes.Brake_Disc_FR_Brake_Disc_0.geometry} material={materials.Brake_Disc} rotation={[0, 0, 2.513]} scale={0.402} />
        <mesh geometry={nodes.Tire_FR_TireMaterial_0.geometry} material={materials.TireMaterial} rotation={[Math.PI / 2, 0.942, Math.PI / 2]} />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1}>
        <mesh geometry={nodes.CarBody_2_Glossy_Plastic_0.geometry} material={materials.Glossy_Plastic} />
        <mesh geometry={nodes.CarBody_2_Plastic_0.geometry} material={materials.Plastic} />
        <mesh geometry={nodes.CarBody_2_Rubber_0.geometry} material={materials.Rubber} />
        <mesh geometry={nodes.CarBody_2_WindowBorder_0.geometry} material={materials.WindowBorder} />
        <mesh geometry={nodes.CarBody_2_Wipers_0.geometry} material={materials.Wipers} />
        <mesh geometry={nodes.CarBody_2_CorvetteWingEmblem_0.geometry} material={materials.CorvetteWingEmblem} />
        <mesh geometry={nodes.CarBody_2_Chrome_0.geometry} material={materials.Chrome} />
        <mesh geometry={nodes.CarBody_2_Shadow_0.geometry} material={materials.Shadow} />
        <mesh geometry={nodes.CarBody_2_Mesh_0.geometry} material={materials.Mesh} />
        <mesh geometry={nodes.CarBody_2_Side_Mirrors_0.geometry} material={materials.Side_Mirrors} />
        <mesh geometry={nodes.CarBody_2_Reflectors_0.geometry} material={materials.Reflectors} />
        <mesh geometry={nodes.CarBody_2_Tail_Lights_White_Cover_0.geometry} material={materials.Tail_Lights_White_Cover} />
        <mesh geometry={nodes.CarBody_2_Tail_Lights_Red_Cover_0.geometry} material={materials.Tail_Lights_Red_Cover} />
        <mesh geometry={nodes.CarBody_2_Daylight_Cover_0.geometry} material={materials.Daylight_Cover} />
        <mesh geometry={nodes.CarBody_2_Spoiler_Light_Cover_0.geometry} material={materials.Spoiler_Light_Cover} />
        <mesh geometry={nodes.CarBody_2_Main_Headlight_Lens_0.geometry} material={materials.Main_Headlight_Lens} />
        <mesh geometry={nodes.CarBody_2_Blinker_Glass_Cover_0.geometry} material={materials.Blinker_Glass_Cover} />
        <mesh geometry={nodes.CarBody_2_Tail_Lights_Red_Cover_2_0.geometry} material={materials.Tail_Lights_Red_Cover_2} />
        <mesh geometry={nodes.CarBody_2_Side_Reflectors_Cover_0.geometry} material={materials.Side_Reflectors_Cover} />
        <mesh geometry={nodes.CarBody_2_Windows_0.geometry} material={materials.Windows} />
        <mesh geometry={nodes.CarBody_2_Headlight_Cover_0.geometry} material={materials.Headlight_Cover} />
        <mesh geometry={nodes.CarBody_2_Exhaust_0.geometry} material={materials.Exhaust} />
        <mesh geometry={nodes.CarBody_2_Exhaust_Housing_0.geometry} material={materials.Exhaust_Housing} />
        <mesh geometry={nodes.CarBody_2_Interior_0.geometry} material={materials.Interior} />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1}>
        <mesh geometry={nodes.CarBody_1_Car_Paint_0.geometry} material={materials.Car_Paint} />
        <mesh geometry={nodes.CarBody_1_Car_Paint_0_1.geometry} material={materials.Car_Paint} />
        <mesh geometry={nodes.CarBody_1_Car_Paint_0_2.geometry} material={materials.Car_Paint} />
        <mesh geometry={nodes.CarBody_1_Car_Paint_2_0.geometry} material={materials.Car_Paint_2} />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1}>
        <mesh geometry={nodes.License_Plate_LicensePlate_Frame_0.geometry} material={materials.LicensePlate_Frame} />
        <mesh geometry={nodes.License_Plate_License_Plate_0.geometry} material={materials.License_Plate} />
      </group>
      <mesh geometry={nodes.Brake_Caliper_FL_Brake_Caliper_0.geometry} material={materials.Brake_Caliper} position={[-1.59, 0.76, 2.7]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[1.06, 1.06, 1.08]} />
      <mesh geometry={nodes.Brake_Caliper_RL_Brake_Caliper_0.geometry} material={materials.Brake_Caliper} position={[-1.59, 0.76, 2.7]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[1.06, 1.06, 1.08]} />
      <mesh geometry={nodes.Brake_Caliper_RR_Brake_Caliper_0.geometry} material={materials.Brake_Caliper} position={[-1.59, 0.76, 2.7]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[1.06, 1.06, 1.08]} />
      <mesh geometry={nodes.Brake_Caliper_FR_Brake_Caliper_0.geometry} material={materials.Brake_Caliper} position={[-1.59, 0.76, 2.7]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[1.06, 1.06, 1.08]} />
      <mesh geometry={nodes.CarBody_3_Undercarriage_0.geometry} material={materials.Undercarriage} rotation={[-Math.PI / 2, 0, 0]} scale={1} />
    </group>
  )
})

// Set display name for debugging purposes
CarModel.displayName = 'CarModel';
useGLTF.preload('/models/car.glb')
